spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: pjtec-api-biblioteca

  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATA_SOURCE_URL}
    username: ${SPRING_DATA_SOURCE_USERNAME}
    password: ${SPRING_DATA_SOURCE_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:migration
    fail-on-missing-locations: true
  jpa:
    show-sql: true

server:
  port: ${SERVER_PORT}